#!/bin/bash
function print_usage {
  echo "Usage: `basename $0` infofiles#.geo output_tecplot_file"
  echo "Example:"
  echo "  `basename $0` myinfo1.geo myinfo2.geo infos.tec"
}
if [ $# -lt 2 ] ; then
  print_usage
  exit
fi
fou=${BASH_ARGV[0]}
echo 'VARIABLES="x" "y" "z"' > $fou
while [ $# -gt 1 ]; do
  echo "Parsing file $1"
  while read line ; do
    if echo $line | grep -q domain ; then
      zone=`echo $line | awk '{print $1}'`
      Ni=`echo $line | awk '{print $2}'`
      Nj=`echo $line | awk '{print $3}'`
      Nk=`echo $line | awk '{print $4}'`
      echo 'ZONE T="'$zone'" I='$Ni' J='$Nj' K='$Nk >> $fou
      echo $zone
    else
      echo $line >> $fou
    fi
  done < $1
  shift
done
exit 0
