#!/bin/bash
#===============================================================================
#
#          FILE:  nef_rename
# 
#         USAGE:  ./nef_rename 
# 
#   DESCRIPTION:  
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:   (), 
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  09/15/2011 03:58:44 PM CEST
#      REVISION:  ---
#===============================================================================


for file in $( ls *.[nN][eE][fF] ); do
  newname=`exiftool -s -DateTimeOriginal $file | awk '{print $3":"$4}' | awk -F : '{print $1"_"$2"_"$3"-"$4"_"$5"_"$6}'`
  echo "Rename $file in $newname.nef" 
  mv $file $newname.nef 
done
