#!/bin/bash
# File: /home/stefano/.scripts/nef_rename
# Author: Stefano Zaghi <stefano.zaghi@gmail.com>
# Date: 29.08.2017
# Last Modified Date: 25.09.2017
# Last Modified By: Stefano Zaghi <stefano.zaghi@gmail.com>
for file in $( ls *.[nN][eE][fF] ); do
   newname=`exiftool -s -DateTimeOriginal $file | awk '{print $3":"$4}' | awk -F : '{print $1"_"$2"_"$3"-"$4"_"$5"_"$6}'`
   if [[ -e $newname.nef ]] ; then
       i=0
       while [[ -e $newname-$i.nef ]] ; do
          let i++
       done
       newname=$newname-$i
   fi
   echo "Rename $file in $newname.nef"
   mv $file $newname.nef
done
