#!/bin/bash
function print_usage {
  echo "Usage: `basename $0` input_body_file output_tecplot_file"
  echo "Examples:"
  echo "  `basename $0` mybody.dat body.tec"
}
if [ $# -eq 0 ] ; then
  print_usage
  exit
fi
fin=$1
fou=$2
echo 'VARIABLES="x" "y" "z"' > $fou
n=0
npt=0
np=0
Nb=0
while read line ; do
  n=$(($n + 1))
  if [ $n == 1 ] ; then
    npt=$line
    npt=$(($npt + 1))
  elif [ $n -gt $npt ] ; then
    break
  else
    np=$(($np + 1))
    if [ $np == 1 ] ; then
      Nb=$(($Nb + 1))
      Nbp=`printf "%4.4d" $Nb`
      echo 'ZONE T="body_'$Nbp'" I=2, J=2, K=2' >> $fou
    elif [ $np == 8 ] ; then
      np=0
    fi
    echo $line >> $fou
  fi
done < "$fin"
