# ~/.bash_aliases

alias ls='ls --color=auto'
alias ll='ls -lh'
alias lt='ls -rtlh'
alias lS='ls -rtlhS'
alias la='ls -A'
alias l="ls -lF --color=auto"
alias lsUUID='sudo blkid'
alias dir='ls --format=vertical'
alias vdir='ls --format=long'
alias cp='cp -iv'
alias rm='rm -iv'
alias mv='mv -iv'
alias cd..='cd ..'
alias ..='cd ..'
alias grep="grep --color=auto"

# pacman/yaourt
alias pacman-clean='sudo pacman -Rns $(pacman -Qqtd)'
alias yaourt-update='yaourt -Syu ; yaourt -Su --aur'
alias yaourt-all='yaourt -Syu --aur'

# make
alias make='make -j 10'

# okular
alias okular='okular > /dev/null 2>&1'

# evince
alias evince='evince > /dev/null 2>&1'

# gimp
alias gimp='gimp > /dev/null 2>&1'

# eog
alias eog='eog > /dev/null 2>&1'

# latexmk
alias latexmk='latexmk -pdf'

# pdflatex
alias pdflatex='pdflatex -interaction=nonstopmode -halt-on-error'

# git
alias pushgithub-master='git push -u origin master --tags'
alias pushgithub-AMR='git push -u origin AMR --tags'
alias pushgithub-gh-pages='git push -u origin gh-pages'
alias pushgithub-testing='git push -u origin testing --tags'
alias pushgithub-master-local='git push -u zaghi-local master --tags'

# acroread
alias acroread='acroread > /dev/null 2>&1'

# vim SuperMan!
vman() {
  vim -c "SuperMan $*"

  if [ "$?" != "0" ]; then
    echo "No manual entry for $*"
  fi
}

# yapf
alias yapf='python -m yapf --style=/home/stefano/python/yapf-style.ini'

#Aliases for CRESCO connections
alias n.por='ssh nunzio@cresco1-f1.portici.enea.it'
alias n.por3='ssh nunzio@cresco3x001.portici.enea.it'
alias n.por4='ssh nunzio@cresco4x001.portici.enea.it'
alias n.cas='ssh nunzio@crescoc1.casaccia.enea.it'
alias r.por='ssh picchia@cresco1-f1.portici.enea.it'
alias r.por3='ssh picchia@cresco3x001.portici.enea.it'
alias r.por4='ssh picchia@cresco4x001.portici.enea.it'
alias r.cas='ssh picchia@crescoc1.casaccia.enea.it'
alias e.por='ssh eugenio@cresco1-f1.portici.enea.it'
alias e.por3='ssh eugenio@cresco3x001.portici.enea.it'
alias e.por4='ssh eugenio@cresco4x001.portici.enea.it'
alias e.cas='ssh eugenio@crescoc1.casaccia.enea.it'

#Miscellanea
alias hist='history -a && hist.py'
