[Appearance]
style=Fusion
color_scheme_path=/home/stefano/.config/qt6ct/colors/noctalia.conf
custom_palette=true
standard_dialogs=default

[Interface]
menus_have_icons=true
show_shortcuts_in_context_menus=true
