[Appearance]
color_scheme_path=/home/stefano/.config/qt6ct/colors/noctalia.conf
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
menus_have_icons=true
show_shortcuts_in_context_menus=true

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xfb\0\0\x2\xe0\0\0\0\0\0\0\0\0\0\0\x4\xfb\0\0\x2\xe0\0\0\0\0\0\0\0\0\x5\0\0\0\0\0\0\0\0\0\0\0\x4\xfb\0\0\x2\xe0)
